#!/usr/bin/env bash
# bin/compile <build-dir> <cache-dir>

function indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";;
    *)      sed -u "$c";;
  esac
}

BUILD_DIR=$1
CACHE_DIR=$2

apt-get install -y libqtwebkit-dev qt4-qmake
